services:
  core-postgres:
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=stellar
    expose:
      - "5641"
    command: [ "-p", "5641" ]

  core:
    platform: linux/amd64
    # Note: Please keep the image pinned to an immutable tag matching the Captive Core version.
    #       This avoids implicit updates which break compatibility between
    #       the Core container and captive core.
    image: ${CORE_IMAGE:-stellar/unsafe-stellar-core:21.0.1-1897.dfd3dbff1.focal}
    depends_on:
      - core-postgres
    environment:
      - TRACY_NO_INVARIANT_CHECK=1
    ports: # we omit the host-side ports to allocate them dynamically
      # peer
      - "127.0.0.1:0:11625"
      # http
      - "127.0.0.1:0:11626"
      # history archive
      - "127.0.0.1:0:1570"
    entrypoint: /usr/bin/env
    command: /start standalone
    volumes:
      - ./stellar-core-integration-tests.cfg:/stellar-core.cfg
      - ./core-start.sh:/start
    extra_hosts:
      - "host.docker.internal:host-gateway"
