name: Dependency sanity checker

on:
  push:
    branches: [ main, release/** ]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  dependency-sanity-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: stellar/actions/rust-cache@main
      - uses: ./.github/actions/setup-go
      - run: scripts/check-dependencies.bash

  validate-rust-git-rev-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stellar/actions/rust-check-git-rev-deps@main
