# workaround to simplify terraform management of required status checks,
# see https://github.com/orgs/community/discussions/12377
name: "Required status check"
on:
  pull_request:

jobs:
  complete:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: int128/wait-for-workflows-action@8aa9c53102cda84041a879b99a88b2a93721231d # v1.10.0
        with:
          filter-workflow-names: |
            Dependency sanity checker*
            Go*
            Rust*
            Soroban RPC*
