name: Rust

on:
  push:
    branches: [ main, release/** ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: stellar/actions/rust-cache@main
      - run: make rust-check
      - run: make rust-test
